

services:
    tellastory_db:
        container_name: tellastory_prod_db
        image: postgres:latest
        env_file:
            - secrets.env
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    storyteller_backend_prod:
        container_name: storyteller_backend_prod
        image: <nameOfBackendProdBuild>
        env_file:
            - secrets.env
        build:
            context: .
            dockerfile: ./BackEnd/prod.Dockerfile
    nginx_prod:
        container_name: nginx_prod
        image: <nameOfCustomNginxBuild>
        depends_on:
            - storyteller_backend_prod
            - tellastory_db
        ports:
            - 8080:80
    volumes:
            db-data:
