services:
    tellastory_db:
        container_name: tellastory_db
        image: postgres:latest
        environment:
            - POSTGRES_DB=tellastory_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=verySecurePassword
        ports:
            - 1338:5432
    tellastory_test_db:
        container_name: tellastory_test_db
        image: postgres:latest
        environment:
            - POSTGRES_DB=tellastory_test_db
            - POSTGRES_USER=test_admin
            - POSTGRES_PASSWORD=testDBPassword
        ports:
            - 1339:5432
volumes:
    postgres-db:
        driver: local 
