services:
    tellastory_db:
        container_name: tellastory_db
        image: postgres:latest
        environment:
            - POSTGRES_DB=tellastory_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=verySecurePassword
        ports:
            - 1338:5432

volumes:
    postgres-db:
        driver: local 
