name: Development pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    initial_pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build development env and test it
              run: ls
